#!/bin/bash

projectDirs="db2phplib db2phpnb db2phpcli"

#cleanup
for pdir in $projectDirs; do
	(
	cd $pdir;
	mvn clean
	)
done

# create source tarball
#./tarsrc || exit 1

# build
for pdir in $projectDirs; do
	(
	cd $pdir;
	mvn  -Prelease-profile install
	)
done

# upload
./upload || exit 1

# NetBeans plugin page? curl maybe?

# SPAM!
echo "spam:"
./spam
