#!/bin/bash
if [ ! -f "googlecode_upload_py3k.py" ]; then
	wget http://support.googlecode.com/svn/trunk/scripts/googlecode_upload_py3k.py
	chmod +x googlecode_upload_py3k.py
	#wget http://support.googlecode.com/svn/trunk/scripts/googlecode_upload.py
	#chmod +x googlecode_upload.py
fi

# parse version
. .version || exit 1

# upload
echo "upload ${VERSION}:"
. .passwd || exit 1

upcmd="python3 ./googlecode_upload_py3k.py -p $GPROJECT -u $GUSER -w $GPASSWORD"
#echo $upcmd
$upcmd -s "Source code v${VERSION}" -l "OpSys-All,Type-Source,Featured" "db2php-${VERSION}.tar.bz2" || exit 1
$upcmd -s "NetBeans plugin v${VERSION}" -l "OpSys-All,Type-Package,NetBeans,Featured" "db2phpnb/target/db2phpnb-${VERSION}.nbm" || exit 1
$upcmd -s "CLI v${VERSION}" -l "OpSys-All,Type-Executable,Featured" "db2phplib/target/db2php-cli-${VERSION}.jar" || exit 1
