/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.afraid.poison.db2php;

import java.io.File;
import javax.swing.JPanel;
import org.openide.WizardDescriptor;

public final class PhpClassUtilityVisualPanel1 extends JPanel {

	private WizardDescriptor wizard;

	/** Creates new form PhpClassUtilityVisualPanel1 */
	public PhpClassUtilityVisualPanel1(WizardDescriptor wizard) {
		initComponents();
		setWizard(wizard);
	}

	@Override
	public String getName() {
		return "Step #1";
	}

	/**
	 * @return the wizard
	 */
	public WizardDescriptor getWizard() {
		return wizard;
	}

	/**
	 * @param wizard the wizard to set
	 */
	public void setWizard(WizardDescriptor wizard) {
		this.wizard=wizard;
		getFileSelectionPanel().setWizard(wizard);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileSelectionPanel = new org.afraid.poison.db2php.FileSelectionPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.afraid.poison.db2php.FileSelectionPanel fileSelectionPanel;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the directory
	 */
	public File getDirectory() {
		return getFileSelectionPanel().getDirectory();
	}

	/**
	 * @return the fileSelectionPanel
	 */
	private FileSelectionPanel getFileSelectionPanel() {
		return fileSelectionPanel;
	}
}

